### ISSUE TITLE
Refactor application

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-website-client#1]
**Description**
Buildout new `create-react-app` from scratch and refactor for react hooks.

**Tasks**
- [x] Create a new `create-react-app`.
- [x] Build new app.
- [ ] Refactor for React Hooks.
